CREATE TABLE IF NOT EXISTS usuario (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre text NOT NULL CHECK ( nombre <> '' ),
    apellido text NOT NULL CHECK ( apellido <> '' ),
    correo text NOT NULL CHECK ( correo <> '' ),
    direccion text NOT NULL CHECK ( direccion <> '' ),
    telefono text,
    cargo text,
    activo boolean 
);

CREATE TABLE IF NOT EXISTS sesion (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    contrasenia text NOT NULL CHECK ( contrasenia <> '' ),
    token text NOT NULL CHECK ( token <> '' ),
    id_usuario integer REFERENCES usuario ( id ),
    id_rol integer REFERENCES rol ( id )
);

CREATE TABLE IF NOT EXISTS publicar (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    fecha_publicacion date NOT NULL,
    disponible boolean
);

CREATE TABLE IF NOT EXISTS tipo_rol (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre_rol text NOT NULL CHECK ( nombre_rol <> '' )
);

CREATE TABLE IF NOT EXISTS rol (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id_tipo_rol integer REFERENCES rol ( id ), 
    id_sesion integer REFERENCES sesion ( id )
);

CREATE TABLE IF NOT EXISTS documento (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre text NOT NULL CHECK ( nombre <> '' ), 
    ruta text NOT NULL CHECK ( ruta <> '' ),
    id_usuario integer REFERENCES usuario ( id ),
    id_publicacion integer REFERENCES publicar ( id )
);

